<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \HappyHorizon\PersistentGraphQlSchema\Block\Cache\GraphqlFlushButton $block */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */

$message = __('Are you sure you want to Flush the GraphqlSchema? Note that this might cause site temporary to go slow!');
$url = $block->getFlushUrl();
?>
<p>
    <button id="flushGraphqlSchema" type="button">
        <?= __("Flush GraphqlSchema") ?>
    </button>
    <?= /* @noEscape */ $secureRenderer->renderEventListenerAsTag(
        'onclick',
        'confirmSetLocation(\''.$message.'\', \''.$url.'\')',
        'button#flushGraphqlSchema'
    ) ?>
    <span><?= $block->escapeHtml(__('Flush GraphqlSchema files')); ?></span>
</p>
